# reBotArm 夹爪配置文件

channel: /dev/ttyACM0

gripper:
  - name: gripper
    motor_id: 0x07
    feedback_id: 0x17
    model: "4310"
    vendor: "damiao"
    MIT:
      kp: 8.0
      kd: 1.0
    POS_VEL:
      vel_kp: 0.0008
      vel_ki: 0.002
      pos_kp: 50.0
      pos_ki: 1.0
      vlim: 3.0
